name: "CI"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Nix Cache
      uses: actions/cache@v3
      with:
        path: nix-store-cache
        key: nix-store-cache-${{ github.sha }}
        # fall back to (latest) previous cache
        restore-keys: |
          nix-store-cache
    - run: |
        cp -r nix-store-cache nix-store-cache-copy || true
    - uses: cachix/install-nix-action@v18
      with:
        # https://github.com/NixOS/nix/issues/6572
        install_url: https://releases.nixos.org/nix/nix-2.7.0/install
        extra_nix_config: |
          substituters = file://${{ github.workspace }}/nix-store-cache-copy?priority=10&trusted=true https://cache.nixos.org/
    - name: Install Cachix
      uses: cachix/cachix-action@v12
      with:
        name: lean4
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        skipPush: true  # we push specific outputs only
    - name: Build
      id: build
      run: |
        nix flake lock --update-input lake2nix  # HACK
        nix build ./lake2nix -Lvo push
        nix build . -Lv
      shell: nix run .#ciShell -- bash -euxo pipefail {0}
    - name: Push to Cachix
      run: |
        [ -z "${{ secrets.CACHIX_AUTH_TOKEN }}" ] || cachix push -j4 lean4 ./push* || true
    - name: Rebuild Nix Store Cache
      run: |
        rm -rf nix-store-cache || true
        nix copy ./push* ./result ./lake2nix#oTree --to file://$PWD/nix-store-cache?compression=none
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: nale
        path: result/bin

  bench:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          path: nale
      - name: Bench
        run: |
          ln -s nale/nix-portable ./nix
          chmod u+x ./nix
          export PATH=.:$PATH
          alias bench='\time -f "%e %M" -ao times'
          bench nix build nale+github:leanprover-community/mathlib4/5f78e345#Mathlib --override-input lean github:Kha/lean4/nale -v
          bench nix build nale+github:leanprover-community/mathlib4/5f78e345#Mathlib --override-input lean github:Kha/lean4/nale -v
          bench nix flake clone nale+github:leanprover-community/mathlib4 --dest mathlib4
          cd mathlib4
          git checkout 5f78e345
          bench nix build nale+git+file:$PWD --override-input lean github:Kha/lean4/nale -v
          echo >> README.md
          bench nix build nale+git+file:$PWD --override-input lean github:Kha/lean4/nale -v
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
