name: "CI"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Nix Cache
      uses: actions/cache@v3
      with:
        path: nix-store-cache
        key: ${{ matrix.name }}-nix-store-cache-${{ github.sha }}
        # fall back to (latest) previous cache
        restore-keys: |
          ${{ matrix.name }}-nix-store-cache
    - run: |
        cp -r nix-store-cache nix-store-cache-copy || true
    - uses: cachix/install-nix-action@v18
      with:
        # https://github.com/NixOS/nix/issues/6572
        install_url: https://releases.nixos.org/nix/nix-2.7.0/install
        extra_nix_config: |
          extra-substituters = file://${{ github.workspace }}/nix-store-cache-copy?priority=10&trusted=true https://lean4.cachix.org/
          extra-trusted-public-keys = lean4.cachix.org-1:mawtxSxcaiWE24xCXXgh3qnvlTkyU7evRRnGeAhD4Wk=
    - run: |
        nix flake lock --update-input lake2nix  # HACK
        nix build .#nix-nale ./lake2nix -Lv
      shell: nix run .#ciShell -- bash -euxo pipefail {0}
    - name: Rebuild Nix Store Cache
      run: |
        rm -rf nix-store-cache || true
        nix copy ./result* --to file://$PWD/nix-store-cache?compression=none
